// schema/File.js
import mongoose from "mongoose";
import { getServerSettings } from "#methods/settings/schemaHelpers.js";
const { Schema } = mongoose;

const FileSchema = new Schema(
  {
    id: { type: String, unique: true }, // file:abc123@domain (auto-generated by pre-save hook)
    actorId: { type: String, required: true }, // @user@domain
    parentObject: { type: String }, // ID of post/page/etc this file belongs to
    originalFileName: { type: String }, // Original filename from upload
    name: { type: String }, // Title/display name
    summary: { type: String }, // Alt text/description
    type: { type: String }, // Image, Video, Audio, Document
    mediaType: { type: String }, // MIME type (e.g., image/jpeg)
    extension: { type: String },
    to: { type: String, default: "@public" }, // Visibility — same addressing as Post.to
    url: { type: String, required: true }, // App-proxied URL to the file
    storageKey: { type: String }, // Storage adapter key for retrieval/deletion
    thumbnails: { type: Schema.Types.Mixed }, // { '200': storageKey, '400': storageKey }
    server: { type: String }, // domain or server label
    size: { type: Number }, // File size in bytes
    width: { type: Number }, // Image/video width in pixels
    height: { type: Number }, // Image/video height in pixels
    blurhash: { type: String }, // BlurHash string for progressive loading
    processingStatus: {
      type: String,
      enum: ['pending', 'processing', 'ready', 'failed'],
      default: 'ready',
      index: true,
    },
    deletedAt: { type: Date, default: null }, // If the object is deleted, when it was deleted
    // Bumped on each successful GET /files/:id serve (routes/files/serve.js).
    // Only meaningfully used for remote-cache expiry (methods/gc/index.js) —
    // an LRU signal so an actively-viewed cached copy of another server's
    // media survives longer than a flat time-since-cached TTL. Real local
    // uploads are never expired regardless of this field (see gc/index.js).
    lastViewed: { type: Date, default: null },
  },
  { timestamps: true }
);

FileSchema.pre("save", async function (next) {
  try {
    const { domain, actorId } = getServerSettings();

    // Generate ID if not present
    if (!this.id && domain) {
      this.id = `file:${this._id}@${domain}`;
    }

    // Set server if not present
    if (!this.server && actorId) {
      this.server = actorId;
    }

    next();
  } catch (err) {
    next(err);
  }
});

const File = mongoose.model("File", FileSchema);
export default File;
